### ISSUE TITLE
Restruct your code

### ISSUE THREAD

**Issue by ghost** [centr82009/Calculator#1]
I think this code is unreadable. You need split all your files (tests, mv, calculator logic) and use the popular code guide.

**Comment by centr82009** [comment]
The code is written using Swift API Guideline files divided, could you clarify what exactly you don't like

**Comment by RoflanDaniil** [comment]
1. Long lines and comments in AppDelegate.swift, it's unreadable
2. You don't use one code style, for example [here](https://github.com/centr82009/Calculator/blob/5838d04b224c7959a4c03b4be44716987b351121/Calculator/CalculatorBrain.swift#L22) you dont use space before { and use before (
but [here](https://github.com/centr82009/Calculator/blob/5838d04b224c7959a4c03b4be44716987b351121/Calculator/CalculatorBrain.swift#L26) conversely. I've seen this very often in your code. I think your should use some auto code corrector. It's very important !
3. Every thing should be tested in a different file

**Comment by centr82009** [comment]
АХАХАХХАХА, чувак  ты конченый, почитай свифт гайдлайн, с апделегейта коментов я умер, и то что спейс один пропустил, успокойся чувак, полную хуйню написал
